### ISSUE TITLE
No Unit Test Setup

### ISSUE THREAD

**Issue by marpstar** [tomwayson/angular2-esri-example#17]
This code has been immensely helpful to me. One thing that is missing is unit tests.  I have code working that will setup and execute Angular2 unit tests using Jasmine and Karma.  If you're okay with that combo for unit testing, I'd be willing to put together a pull request.

**Comment by tomwayson** [comment]
I'd gladly except a PR w/ the set up for Jasmine/Karma unit tests. Thanks!

**Comment by dgwaldo** [comment]
Looks like this might have been dropped?  I'd be willing to do it if I can figure it out :)  Hopefully by this weekend...

**Comment by tomwayson** [comment]
Thanks @dgwaldo

This should be a little more straightforward than https://github.com/tomwayson/esri-webpack-babel/issues/5 b/c you don't have to modify the test karma/webpack config to use babel instead of TypeScript. So it's really just [all but the first step that I outlined there](https://github.com/tomwayson/esri-webpack-babel/issues/5#issuecomment-260380954).

Don't hesitate to ping me if you get stuck on anything.

**Comment by jwerts** [comment]
@tomwayson @dgwaldo - I had set up similar for a project recently, so it was quick to drop that in here - created a PR.

Webpack seems to be working out better than SystemJS for me in general.

**Comment by tomwayson** [comment]
@jwerts awesome! I'll review/merge tonight.

I agree that at least as far as ArcGIS API for JavaScript + Angular2 integration, webpack seems to have a better story at this point than SystemJS - mainly b/c of [the build issue](https://github.com/Esri/esri-system-js/issues/22). It also seems like the Angular2 community at large is moving towards webpack and away from SystemJS - esp since angular-cli now uses webpack.

Speaking of, have you had a chance to check out https://github.com/tomwayson/angular-cli-esri/?

**Comment by jwerts** [comment]
@tomwayson I looked at the mentioned cli project and I'm not a fan of the esriLoader approach.  It's a reasonable approach if the map is a small part of the project, but very cumbersome for a map-centric app and I never had good luck wiring up tests with it in Angular 1.  I'm really enjoying not worrying about the asynchronous nature of esri AMD w/ angular 2 webpack and systemjs and have no desire to go back to explicit dojo requires or esriLoader approach.  Hopefully, the angular cli project will better expose the webpack config in the future (or esri will ditch dojo.... please?).  I don't think we're the only ones who will find that very constraining.  Until then, I'll stick with custom webpack project/config.

**Comment by tomwayson** [comment]
Thanks for the feedback @jwerts!

What's great is that the community has come up w/ a few workarounds for the Dojo AMD problem and we have options.
