### ISSUE TITLE
init.js:31 Error: multipleDefine(…) src: dojoLoader

### ISSUE THREAD

**Issue by dyh333** [tomwayson/angular2-esri-example#26]
hi, @tomwayson . i have try your example and it runs ok. but i when i try put arcgis api into my project, it shows an error shown like title, when add the  <script src="https://js.arcgis.com/3.16/"></script> into index.html. do you know why? 

ps: does it matter if the output.libraryTarget is set to umd in webpack.config.js?

![image](https://cloud.githubusercontent.com/assets/1221313/18825926/5935ae0e-83fd-11e6-82c6-964062b0c37b.png)

**Comment by tomwayson** [comment]
I would expect umd to work. I assume you tried `amd` to resolve this issue, right?

Other than that, what changes did you make between this set up and that of your project? Does your index.html load other script tags besides the ArcGIS API for JavaScript? The `multipleDefine` error is commonly seen when other UMD libraries are loaded on the page _before_ the ArcGIS API for JavaScript. Any of [these suggestions](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=arcgis%20multipledefine%20dojoloader) (placement of script tags, using `defer` on the ArcGIS script tag) might work in your case.

**Comment by dyh333** [comment]
@tomwayson thank you for your reply. yes, i have tried amd, but still failed. and i tried to using defer on the ArcGIS script tag, the multipleDefine error is not display, but it seems not load arcgis module success yet.  
i have commit my test project to github(https://github.com/dyh333/ng2-arcgis-test). the project is forked from angular2-webpack-starter(https://github.com/AngularClass/angular2-webpack-starter). and what i changed is list below:
1. add arcgis script and css path in src/index.html
2. add externals config in config/webpack.common.js #304
3. change output.libraryTarget var to umd in config/webpack.dev.js #97 
4. add typings.json file which is copy from your repo, and run typings install

after that, i tried to import esri/map module in src/about/about.component.ts #4, and in ngAfterViewInit function, load a simple basemap.

and run npm install;  npm start to debug by webpack-dev-server.
would you kindly help me have a look what is wrong. i have spent many days to solve it, but failed again and again. thank you very very much.

**Comment by tomwayson** [comment]
One thing, I do not see that you're [index.html](https://github.com/dyh333/ng2-arcgis-test/blob/f54afcdf05ee78fc604aef0e7a0d2e5d556b2e31/src/index.html) calls `require()` to load in the bundles the way [this repo does here](https://github.com/tomwayson/angular2-esri-example/blob/e8bd68b685c66a5562a3493851e5bae322a2b8f0/index.html#L23).

If that doesn't work, I would say the best approach is to start w/ a clone of this repo add then the parts of of the the angular2-webpack-starter that you need one by one.

**Comment by hassanqaiser** [comment]
@dyh333 let me know if you want me to try something as I tried various options and remained unlucky.

**Comment by tomwayson** [comment]
Did you already try the two things I suggested in my previous comment? If so, what were the results?

**Comment by hassanqaiser** [comment]
@tomwayson yes I tried both. multipleDefine error solved by using defer in the script tag of arcgis-js-api. Using require in the index.html gives error " Uncaught ReferenceError: require is not defined ". 

In webpack2, bundles are being loaded using script tag.

**Comment by tomwayson** [comment]
I've not tested this approach w/ webpack2, so that may not work at all. For now, I would advise against using that.

In order to use this approach, you _must_ load the bundles via Dojo's `require()`, which will not be defined until the ArcGIS API for JavaScript is loaded on the page. You cannot load the bundles via script tags. Did you place your script with `require()` before or after the ArcGIS script tag?

I know that I need to do a better job of documenting how the hack that allows you use the ArcGIS API for JavaScript w/ Webpack works. In short, we are configuring Webpack to bundle your app code (and optionally vendor code) into a single AMD module that is ultimately loaded by the JSAPI's Dojo loader (via `require()`). When the Dojo loader parses the code in that bundle and comes across an external dependency (i.e. a module in the esri or dojo packages), it is able to resolve that dependency to the corresponding module w/in the built (CDN) ArcGIS API for JavaScript script.

Until you understand how your entire app is being loaded by Dojo that is bundled w/ the ArcGIS API for JavaScript, I would caution against trying to use this technique w/ other boilerplates. If you need functionality from those boilerplates that is not in this repo (testing, multiple build targets, etc) I would  suggest that you start w/ a fork of this repo and add those features one by one.

**Comment by hassanqaiser** [comment]
@tomwayson you are our hero..... loaded modules with require and it worked. yayyyyyyyyyyyy

will write the steps shortly......

@dyh333 can I commit to your code?

**Comment by hassanqaiser** [comment]
@tomwayson I can update your angular2-esri-example with webpack2 ...... I already used that example in one of my project accessible with the link ... https://hassanqaiser.github.io/

**Comment by tomwayson** [comment]
That's great! I'm glad you got it working. Anything you can do to document the steps you needed to take to get it working w/ the angular class angular2 webpack starter would be appreciated. Perhaps you could leave a comment in #27?

Also, good to know that it works w/ webpack2! Your app looks great too.

I'd gladly accept a pull request to update to webpack2.

**Comment by dyh333** [comment]
@hassanqaiser  great! please commit your code, i need it! would you tell me how you solved it?
