### ISSUE TITLE
ClusterLayer

### ISSUE THREAD

**Issue by klanglie** [tomwayson/angular2-esri-example#34]
Hi,

You have a great example. My team is using webpack / Arcgis 3.18 and Angular2. We used your example to help us load the esri / dojo modules. However, we really need to get ClusterLayer working. Could you please show us how or offer advice on how we can integrate one of the following two projects:

https://github.com/Esri/cluster-layer-js

https://github.com/nickcam/FlareClusterLayer

Thanks,
Kai

**Comment by tomwayson** [comment]
This repo shows how to use cluster-layer-js:

https://github.com/tomwayson/esri-webpack-babel#dojo-lbraries

You could probably adopt those patterns to work w/ v3 of FlareClusterLayer b/c it [looks like that library is distributed as something you can load as a Dojo package](https://github.com/nickcam/FlareClusterLayer/blob/a48d61fe30535b7c16d386f9eb560b16901019eb/index_v3.html#L117-L127)

As for his (TypeScript) v4, you could probably adopt [his instructions 4.1](https://github.com/nickcam/FlareClusterLayer#api-v41-notes) to work w/ webpack instead of esri-system-js. I won't be able to help you with that. A while back I [naively assumed that would be an matter of `npm install` and `import`](https://github.com/Esri/angular-esri-map/issues/311#issuecomment-259516165), but my experience trying to publish [angular2-esri-loader](https://github.com/tomwayson/angular2-esri-loader) in a way that it could be easily consumed in an Angular 2 application built w/ webpack (or presumably SystemJS) was so painful that I don't want anything to do with any problems related to publishing or consuming TypeScript libraries for Angular 2.

**Comment by klanglie** [comment]
Issue solved. Thanks!

**Comment by tomwayson** [comment]
That's great. How did you solve it?
