### ISSUE TITLE
Is there a way to avoid the asynchronous way of loading esri modules?

### ISSUE THREAD

**Issue by andrewaston13** [tomwayson/angular2-esri-example#38]
Hi Tom
Nice work!

I have previously used your "esri-system-js" library where I was able to very easily use the JSAPI inside my angular2-angular4 projects, by simply including a

`import {Map} from 'esri/Map';`

Inside my components and not having to bother with asynchronicity.  As we are moving from systemjs to angular2-cli and webpack, this is no longer possible.

Is there any way this kind of JSAPI integration will be possible in future (without system.js)?
Andrew

**Comment by tomwayson** [comment]
If all you want is to use `import` statements instead of promises and callbacks to load esri modules,  [_that's exacly how this repo works_](https://github.com/tomwayson/angular2-esri-example/blob/f176e0824e176a68b2aec2825382bf6cd2b9d25a/app/map.service.ts#L2-L5).

Now, if you're not happy about the use of `require()` in `import arcgisUtils = require('esri/arcgis/utils');` you _may_ be able to use `import * as arcgisUtils  from 'esri/arcgis/utils';`. You'll have to try that on your own b/c I'm not really up to date on the latest oddities of how you write `import` statements in TypeScript that properly transpile to AMD `require()`/`define()` blocks.

Keep in mind that those transpiled AMD `require()`/`define()` blocks may at runtime actually load some esri modules asynchronously.  In all likelihood that's a good thing. Even if you could actually include esri modules in your bundles like you do w/ other JS libs, you probably wouldn't want to. See this [blog post](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/) for more info.

Now, I see you are using "angular2-cli", which in the past didn't let you modify the webpack config so so that you could make the hacks required to get the above `import` statements working. I'm going to assume you mean the latest version of [@angular/cli](https://cli.angular.io/) which [should let you eject and modify the webpack config](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/#comment-3163968615), or may have other ways of letting you add those configurations via it's API.

> Is there any way this kind of JSAPI integration will be possible in future (without system.js)?

Yes! The future is now. Or more precisely, the future is Nov 2016.

If you're determined try to bundle esri modules, I know that @odoe has been experimenting with this webpack plugin:

https://github.com/OpenNTF/dojo-webpack-plugin/issues/35

I'm not sure if he's gotten it working yet or not.
